baseURL = 'https://tomrake.github.io/sdl-loader/'
languageCode = 'en-us'
title = 'SDL 1.2 release loading.'
theme = "m10c"

author = "Tom Rake"
[params]
  description = "Load sdl libraries from a release."
  avatar = "2665605.jfif"

[[params.social]]
  icon = "github-dark"
  name = "Github"
  url = "https://github.com/tomrake"

[[params.social]]
  icon = "reddit"
  name = "tomrake"
  url = "https://reddit.com/user/tomrake"

[[params.social]]
  icon = "mastodon"
  name = "Mastodon"
  url = "https://mastodon.social/@tomrake"

[[params.social]]
  icon = "discord"
  name = "Discord"
  url = "https://discordapp.com/users/tomrake1957#0816"

[[menu.main]]
 name = "Home"
 url = "/"
 weight = "10"


[[menu.main]]
 name = "About"
 url = "/about/"
 weight = "20"

[[menu.main]]
 name = "Blog"
 url = "/posts/"
 weight = "30"

[[menu.main]]
 name = "Results-01"
 url = "/results-01/"
 weight = "40"